language: python
python:
- '3.10'
install: pip install -r setup/requirements.txt
script: cd test; nosetests
before_install:
- openssl aes-256-cbc -K $encrypted_2931867a4314_key -iv $encrypted_2931867a4314_iv
  -in test/oauth_client.pkl.enc -out test/oauth_client.pkl -d
